package com.acne.model;

import java.io.Serializable;
import java.util.Date;

public class AcneImage implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_acne_images.imageId
	 *
	 * @mbggenerated
	 */
	private Long imageid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_acne_images.acneUserId
	 *
	 * @mbggenerated
	 */
	private Long acneuserid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_acne_images.postTime
	 *
	 * @mbggenerated
	 */
	private Date posttime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_acne_images.path
	 *
	 * @mbggenerated
	 */
	private String path;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_acne_images
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_acne_images.imageId
	 *
	 * @return the value of t_acne_images.imageId
	 *
	 * @mbggenerated
	 */
	public Long getImageid() {
		return imageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_acne_images.imageId
	 *
	 * @param imageid
	 *            the value for t_acne_images.imageId
	 *
	 * @mbggenerated
	 */
	public void setImageid(Long imageid) {
		this.imageid = imageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_acne_images.acneUserId
	 *
	 * @return the value of t_acne_images.acneUserId
	 *
	 * @mbggenerated
	 */
	public Long getAcneuserid() {
		return acneuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_acne_images.acneUserId
	 *
	 * @param acneuserid
	 *            the value for t_acne_images.acneUserId
	 *
	 * @mbggenerated
	 */
	public void setAcneuserid(Long acneuserid) {
		this.acneuserid = acneuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_acne_images.postTime
	 *
	 * @return the value of t_acne_images.postTime
	 *
	 * @mbggenerated
	 */
	public Date getPosttime() {
		return posttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_acne_images.postTime
	 *
	 * @param posttime
	 *            the value for t_acne_images.postTime
	 *
	 * @mbggenerated
	 */
	public void setPosttime(Date posttime) {
		this.posttime = posttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_acne_images.path
	 *
	 * @return the value of t_acne_images.path
	 *
	 * @mbggenerated
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_acne_images.path
	 *
	 * @param path
	 *            the value for t_acne_images.path
	 *
	 * @mbggenerated
	 */
	public void setPath(String path) {
		this.path = path == null ? null : path.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_images
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		AcneImage other = (AcneImage) that;
		return (this.getImageid() == null ? other.getImageid() == null : this.getImageid().equals(other.getImageid()))
				&& (this.getAcneuserid() == null ? other.getAcneuserid() == null
						: this.getAcneuserid().equals(other.getAcneuserid()))
				&& (this.getPosttime() == null ? other.getPosttime() == null
						: this.getPosttime().equals(other.getPosttime()))
				&& (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_images
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getImageid() == null) ? 0 : getImageid().hashCode());
		result = prime * result + ((getAcneuserid() == null) ? 0 : getAcneuserid().hashCode());
		result = prime * result + ((getPosttime() == null) ? 0 : getPosttime().hashCode());
		result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_images
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", imageid=").append(imageid);
		sb.append(", acneuserid=").append(acneuserid);
		sb.append(", posttime=").append(posttime);
		sb.append(", path=").append(path);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}