package com.acne.model;

import java.io.Serializable;

public class AcneUserArticle implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_acne_article.acneUserArticleId
	 *
	 * @mbggenerated
	 */
	private Long acneuserarticleid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_acne_article.acneUserId
	 *
	 * @mbggenerated
	 */
	private Long acneuserid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_acne_article.articleId
	 *
	 * @mbggenerated
	 */
	private Long articleid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_acne_article
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_acne_article.acneUserArticleId
	 *
	 * @return the value of t_acne_article.acneUserArticleId
	 *
	 * @mbggenerated
	 */
	public Long getAcneuserarticleid() {
		return acneuserarticleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_acne_article.acneUserArticleId
	 *
	 * @param acneuserarticleid
	 *            the value for t_acne_article.acneUserArticleId
	 *
	 * @mbggenerated
	 */
	public void setAcneuserarticleid(Long acneuserarticleid) {
		this.acneuserarticleid = acneuserarticleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_acne_article.acneUserId
	 *
	 * @return the value of t_acne_article.acneUserId
	 *
	 * @mbggenerated
	 */
	public Long getAcneuserid() {
		return acneuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_acne_article.acneUserId
	 *
	 * @param acneuserid
	 *            the value for t_acne_article.acneUserId
	 *
	 * @mbggenerated
	 */
	public void setAcneuserid(Long acneuserid) {
		this.acneuserid = acneuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_acne_article.articleId
	 *
	 * @return the value of t_acne_article.articleId
	 *
	 * @mbggenerated
	 */
	public Long getArticleid() {
		return articleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_acne_article.articleId
	 *
	 * @param articleid
	 *            the value for t_acne_article.articleId
	 *
	 * @mbggenerated
	 */
	public void setArticleid(Long articleid) {
		this.articleid = articleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_article
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		AcneUserArticle other = (AcneUserArticle) that;
		return (this.getAcneuserarticleid() == null ? other.getAcneuserarticleid() == null
				: this.getAcneuserarticleid().equals(other.getAcneuserarticleid()))
				&& (this.getAcneuserid() == null ? other.getAcneuserid() == null
						: this.getAcneuserid().equals(other.getAcneuserid()))
				&& (this.getArticleid() == null ? other.getArticleid() == null
						: this.getArticleid().equals(other.getArticleid()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_article
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getAcneuserarticleid() == null) ? 0 : getAcneuserarticleid().hashCode());
		result = prime * result + ((getAcneuserid() == null) ? 0 : getAcneuserid().hashCode());
		result = prime * result + ((getArticleid() == null) ? 0 : getArticleid().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_article
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", acneuserarticleid=").append(acneuserarticleid);
		sb.append(", acneuserid=").append(acneuserid);
		sb.append(", articleid=").append(articleid);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}