package com.acne.model;

import java.io.Serializable;

public class AcneUserGoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acne_goods.acneUserGoodsId
     *
     * @mbggenerated
     */
    private Long acneusergoodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acne_goods.acneUserId
     *
     * @mbggenerated
     */
    private Long acneuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acne_goods.goodsId
     *
     * @mbggenerated
     */
    private Long goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_acne_goods
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acne_goods.acneUserGoodsId
     *
     * @return the value of t_acne_goods.acneUserGoodsId
     *
     * @mbggenerated
     */
    public Long getAcneusergoodsid() {
        return acneusergoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acne_goods.acneUserGoodsId
     *
     * @param acneusergoodsid the value for t_acne_goods.acneUserGoodsId
     *
     * @mbggenerated
     */
    public void setAcneusergoodsid(Long acneusergoodsid) {
        this.acneusergoodsid = acneusergoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acne_goods.acneUserId
     *
     * @return the value of t_acne_goods.acneUserId
     *
     * @mbggenerated
     */
    public Long getAcneuserid() {
        return acneuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acne_goods.acneUserId
     *
     * @param acneuserid the value for t_acne_goods.acneUserId
     *
     * @mbggenerated
     */
    public void setAcneuserid(Long acneuserid) {
        this.acneuserid = acneuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acne_goods.goodsId
     *
     * @return the value of t_acne_goods.goodsId
     *
     * @mbggenerated
     */
    public Long getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acne_goods.goodsId
     *
     * @param goodsid the value for t_acne_goods.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Long goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acne_goods
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AcneUserGoods other = (AcneUserGoods) that;
        return (this.getAcneusergoodsid() == null ? other.getAcneusergoodsid() == null : this.getAcneusergoodsid().equals(other.getAcneusergoodsid()))
            && (this.getAcneuserid() == null ? other.getAcneuserid() == null : this.getAcneuserid().equals(other.getAcneuserid()))
            && (this.getGoodsid() == null ? other.getGoodsid() == null : this.getGoodsid().equals(other.getGoodsid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acne_goods
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAcneusergoodsid() == null) ? 0 : getAcneusergoodsid().hashCode());
        result = prime * result + ((getAcneuserid() == null) ? 0 : getAcneuserid().hashCode());
        result = prime * result + ((getGoodsid() == null) ? 0 : getGoodsid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acne_goods
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", acneusergoodsid=").append(acneusergoodsid);
        sb.append(", acneuserid=").append(acneuserid);
        sb.append(", goodsid=").append(goodsid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}