package com.acne.model;

import java.io.Serializable;
import java.util.Date;

public class Article implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.articleId
     *
     * @mbggenerated
     */
    private Long articleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.publishDate
     *
     * @mbggenerated
     */
    private Date publishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.viewTimes
     *
     * @mbggenerated
     */
    private Integer viewtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.upTimes
     *
     * @mbggenerated
     */
    private Integer uptimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.downTimes
     *
     * @mbggenerated
     */
    private Integer downtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.available
     *
     * @mbggenerated
     */
    private Integer available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_article
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.articleId
     *
     * @return the value of t_article.articleId
     *
     * @mbggenerated
     */
    public Long getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.articleId
     *
     * @param articleid the value for t_article.articleId
     *
     * @mbggenerated
     */
    public void setArticleid(Long articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.title
     *
     * @return the value of t_article.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.title
     *
     * @param title the value for t_article.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.publishDate
     *
     * @return the value of t_article.publishDate
     *
     * @mbggenerated
     */
    public Date getPublishdate() {
        return publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.publishDate
     *
     * @param publishdate the value for t_article.publishDate
     *
     * @mbggenerated
     */
    public void setPublishdate(Date publishdate) {
        this.publishdate = publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.viewTimes
     *
     * @return the value of t_article.viewTimes
     *
     * @mbggenerated
     */
    public Integer getViewtimes() {
        return viewtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.viewTimes
     *
     * @param viewtimes the value for t_article.viewTimes
     *
     * @mbggenerated
     */
    public void setViewtimes(Integer viewtimes) {
        this.viewtimes = viewtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.upTimes
     *
     * @return the value of t_article.upTimes
     *
     * @mbggenerated
     */
    public Integer getUptimes() {
        return uptimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.upTimes
     *
     * @param uptimes the value for t_article.upTimes
     *
     * @mbggenerated
     */
    public void setUptimes(Integer uptimes) {
        this.uptimes = uptimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.downTimes
     *
     * @return the value of t_article.downTimes
     *
     * @mbggenerated
     */
    public Integer getDowntimes() {
        return downtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.downTimes
     *
     * @param downtimes the value for t_article.downTimes
     *
     * @mbggenerated
     */
    public void setDowntimes(Integer downtimes) {
        this.downtimes = downtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.available
     *
     * @return the value of t_article.available
     *
     * @mbggenerated
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.available
     *
     * @param available the value for t_article.available
     *
     * @mbggenerated
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.content
     *
     * @return the value of t_article.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.content
     *
     * @param content the value for t_article.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Article other = (Article) that;
        return (this.getArticleid() == null ? other.getArticleid() == null : this.getArticleid().equals(other.getArticleid()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getPublishdate() == null ? other.getPublishdate() == null : this.getPublishdate().equals(other.getPublishdate()))
            && (this.getViewtimes() == null ? other.getViewtimes() == null : this.getViewtimes().equals(other.getViewtimes()))
            && (this.getUptimes() == null ? other.getUptimes() == null : this.getUptimes().equals(other.getUptimes()))
            && (this.getDowntimes() == null ? other.getDowntimes() == null : this.getDowntimes().equals(other.getDowntimes()))
            && (this.getAvailable() == null ? other.getAvailable() == null : this.getAvailable().equals(other.getAvailable()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getArticleid() == null) ? 0 : getArticleid().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getPublishdate() == null) ? 0 : getPublishdate().hashCode());
        result = prime * result + ((getViewtimes() == null) ? 0 : getViewtimes().hashCode());
        result = prime * result + ((getUptimes() == null) ? 0 : getUptimes().hashCode());
        result = prime * result + ((getDowntimes() == null) ? 0 : getDowntimes().hashCode());
        result = prime * result + ((getAvailable() == null) ? 0 : getAvailable().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleid=").append(articleid);
        sb.append(", title=").append(title);
        sb.append(", publishdate=").append(publishdate);
        sb.append(", viewtimes=").append(viewtimes);
        sb.append(", uptimes=").append(uptimes);
        sb.append(", downtimes=").append(downtimes);
        sb.append(", available=").append(available);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}