package com.acne.model;

import java.io.Serializable;
import java.util.Date;

public class Goods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goodsId
     *
     * @mbggenerated
     */
    private Long goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goodsName
     *
     * @mbggenerated
     */
    private String goodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.uploadDate
     *
     * @mbggenerated
     */
    private Date uploaddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.browseNum
     *
     * @mbggenerated
     */
    private Integer browsenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.available
     *
     * @mbggenerated
     */
    private Integer available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goodsId
     *
     * @return the value of t_goods.goodsId
     *
     * @mbggenerated
     */
    public Long getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goodsId
     *
     * @param goodsid the value for t_goods.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Long goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goodsName
     *
     * @return the value of t_goods.goodsName
     *
     * @mbggenerated
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goodsName
     *
     * @param goodsname the value for t_goods.goodsName
     *
     * @mbggenerated
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.uploadDate
     *
     * @return the value of t_goods.uploadDate
     *
     * @mbggenerated
     */
    public Date getUploaddate() {
        return uploaddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.uploadDate
     *
     * @param uploaddate the value for t_goods.uploadDate
     *
     * @mbggenerated
     */
    public void setUploaddate(Date uploaddate) {
        this.uploaddate = uploaddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.score
     *
     * @return the value of t_goods.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.score
     *
     * @param score the value for t_goods.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.browseNum
     *
     * @return the value of t_goods.browseNum
     *
     * @mbggenerated
     */
    public Integer getBrowsenum() {
        return browsenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.browseNum
     *
     * @param browsenum the value for t_goods.browseNum
     *
     * @mbggenerated
     */
    public void setBrowsenum(Integer browsenum) {
        this.browsenum = browsenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.available
     *
     * @return the value of t_goods.available
     *
     * @mbggenerated
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.available
     *
     * @param available the value for t_goods.available
     *
     * @mbggenerated
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Goods other = (Goods) that;
        return (this.getGoodsid() == null ? other.getGoodsid() == null : this.getGoodsid().equals(other.getGoodsid()))
            && (this.getGoodsname() == null ? other.getGoodsname() == null : this.getGoodsname().equals(other.getGoodsname()))
            && (this.getUploaddate() == null ? other.getUploaddate() == null : this.getUploaddate().equals(other.getUploaddate()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
            && (this.getBrowsenum() == null ? other.getBrowsenum() == null : this.getBrowsenum().equals(other.getBrowsenum()))
            && (this.getAvailable() == null ? other.getAvailable() == null : this.getAvailable().equals(other.getAvailable()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGoodsid() == null) ? 0 : getGoodsid().hashCode());
        result = prime * result + ((getGoodsname() == null) ? 0 : getGoodsname().hashCode());
        result = prime * result + ((getUploaddate() == null) ? 0 : getUploaddate().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        result = prime * result + ((getBrowsenum() == null) ? 0 : getBrowsenum().hashCode());
        result = prime * result + ((getAvailable() == null) ? 0 : getAvailable().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", goodsid=").append(goodsid);
        sb.append(", goodsname=").append(goodsname);
        sb.append(", uploaddate=").append(uploaddate);
        sb.append(", score=").append(score);
        sb.append(", browsenum=").append(browsenum);
        sb.append(", available=").append(available);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}