package com.acne.model;

import java.io.Serializable;
import java.util.Date;

public class Suggest implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_suggest.suggestionId
	 *
	 * @mbggenerated
	 */
	private Long suggestionid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_suggest.userId
	 *
	 * @mbggenerated
	 */
	private Long userid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_suggest.userType
	 *
	 * @mbggenerated
	 */
	private String usertype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_suggest.suggestTime
	 *
	 * @mbggenerated
	 */
	private Date suggesttime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_suggest.available
	 *
	 * @mbggenerated
	 */
	private Integer available;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_suggest.suggestText
	 *
	 * @mbggenerated
	 */
	private String suggesttext;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_suggest
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_suggest.suggestionId
	 *
	 * @return the value of t_suggest.suggestionId
	 *
	 * @mbggenerated
	 */
	public Long getSuggestionid() {
		return suggestionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_suggest.suggestionId
	 *
	 * @param suggestionid
	 *            the value for t_suggest.suggestionId
	 *
	 * @mbggenerated
	 */
	public void setSuggestionid(Long suggestionid) {
		this.suggestionid = suggestionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_suggest.userId
	 *
	 * @return the value of t_suggest.userId
	 *
	 * @mbggenerated
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_suggest.userId
	 *
	 * @param userid
	 *            the value for t_suggest.userId
	 *
	 * @mbggenerated
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_suggest.userType
	 *
	 * @return the value of t_suggest.userType
	 *
	 * @mbggenerated
	 */
	public String getUsertype() {
		return usertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_suggest.userType
	 *
	 * @param usertype
	 *            the value for t_suggest.userType
	 *
	 * @mbggenerated
	 */
	public void setUsertype(String usertype) {
		this.usertype = usertype == null ? null : usertype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_suggest.suggestTime
	 *
	 * @return the value of t_suggest.suggestTime
	 *
	 * @mbggenerated
	 */
	public Date getSuggesttime() {
		return suggesttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_suggest.suggestTime
	 *
	 * @param suggesttime
	 *            the value for t_suggest.suggestTime
	 *
	 * @mbggenerated
	 */
	public void setSuggesttime(Date suggesttime) {
		this.suggesttime = suggesttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_suggest.available
	 *
	 * @return the value of t_suggest.available
	 *
	 * @mbggenerated
	 */
	public Integer getAvailable() {
		return available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_suggest.available
	 *
	 * @param available
	 *            the value for t_suggest.available
	 *
	 * @mbggenerated
	 */
	public void setAvailable(Integer available) {
		this.available = available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_suggest.suggestText
	 *
	 * @return the value of t_suggest.suggestText
	 *
	 * @mbggenerated
	 */
	public String getSuggesttext() {
		return suggesttext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_suggest.suggestText
	 *
	 * @param suggesttext
	 *            the value for t_suggest.suggestText
	 *
	 * @mbggenerated
	 */
	public void setSuggesttext(String suggesttext) {
		this.suggesttext = suggesttext == null ? null : suggesttext.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_suggest
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Suggest other = (Suggest) that;
		return (this.getSuggestionid() == null ? other.getSuggestionid() == null
				: this.getSuggestionid().equals(other.getSuggestionid()))
				&& (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
				&& (this.getUsertype() == null ? other.getUsertype() == null
						: this.getUsertype().equals(other.getUsertype()))
				&& (this.getSuggesttime() == null ? other.getSuggesttime() == null
						: this.getSuggesttime().equals(other.getSuggesttime()))
				&& (this.getAvailable() == null ? other.getAvailable() == null
						: this.getAvailable().equals(other.getAvailable()))
				&& (this.getSuggesttext() == null ? other.getSuggesttext() == null
						: this.getSuggesttext().equals(other.getSuggesttext()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_suggest
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSuggestionid() == null) ? 0 : getSuggestionid().hashCode());
		result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
		result = prime * result + ((getUsertype() == null) ? 0 : getUsertype().hashCode());
		result = prime * result + ((getSuggesttime() == null) ? 0 : getSuggesttime().hashCode());
		result = prime * result + ((getAvailable() == null) ? 0 : getAvailable().hashCode());
		result = prime * result + ((getSuggesttext() == null) ? 0 : getSuggesttext().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_suggest
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", suggestionid=").append(suggestionid);
		sb.append(", userid=").append(userid);
		sb.append(", usertype=").append(usertype);
		sb.append(", suggesttime=").append(suggesttime);
		sb.append(", available=").append(available);
		sb.append(", suggesttext=").append(suggesttext);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}