package com.acne.dao;

import com.acne.model.AcneUserGoods;

public interface AcneUserGoodsMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_goods
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long acneusergoodsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_goods
	 *
	 * @mbggenerated
	 */
	int insert(AcneUserGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_goods
	 *
	 * @mbggenerated
	 */
	int insertSelective(AcneUserGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_goods
	 *
	 * @mbggenerated
	 */
	AcneUserGoods selectByPrimaryKey(Long acneusergoodsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_goods
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AcneUserGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_goods
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AcneUserGoods record);
}