package com.acne.dao;

import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.acne.model.AcneUser;

public interface AcneUserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_user
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_user
	 *
	 * @mbggenerated
	 */
	int insert(AcneUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_user
	 *
	 * @mbggenerated
	 */
	int insertSelective(AcneUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_user
	 *
	 * @mbggenerated
	 */
	AcneUser selectByPrimaryKey(Long userid);

	AcneUser selectByPhone(Map<String, Object> map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_user
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AcneUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_user
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AcneUser record);

	public void insertViewedArticle(@Param("articleId") Long articleId, @Param("userId") Long userId);

	public void insertViewedGoods(@Param("goodsId") Long goodsId, @Param("userId") Long userId);
}