package com.acne.dao;

import com.acne.model.AcneUserArticle;

public interface AcneUserArticleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_article
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long acneuserarticleid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_article
	 *
	 * @mbggenerated
	 */
	int insert(AcneUserArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_article
	 *
	 * @mbggenerated
	 */
	int insertSelective(AcneUserArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_article
	 *
	 * @mbggenerated
	 */
	AcneUserArticle selectByPrimaryKey(Long acneuserarticleid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_article
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AcneUserArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_article
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AcneUserArticle record);
}