package com.acne.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.acne.model.AcneImage;

public interface AcneImageMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_images
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long imageid);

	void postImages(@Param("path") String path, @Param("userId") Long userId);

	List<AcneImage> getImages(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_images
	 *
	 * @mbggenerated
	 */
	int insert(AcneImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_images
	 *
	 * @mbggenerated
	 */
	int insertSelective(AcneImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_images
	 *
	 * @mbggenerated
	 */
	AcneImage selectByPrimaryKey(Long imageid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_images
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AcneImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_acne_images
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AcneImage record);
}