package com.acne.dao;

import com.acne.model.Suggest;

public interface SuggestMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_suggest
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long suggestionid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_suggest
	 *
	 * @mbggenerated
	 */
	int insert(Suggest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_suggest
	 *
	 * @mbggenerated
	 */
	int insertSelective(Suggest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_suggest
	 *
	 * @mbggenerated
	 */
	Suggest selectByPrimaryKey(Long suggestionid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_suggest
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Suggest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_suggest
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Suggest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_suggest
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Suggest record);
}